2021-07-29 16:13:15|64466|INFO|deephyper:69] 

Loading Deephyper
--------------
2021-07-29 16:13:15|64466|ERROR|deephyper:72] Uncaught exception:
Traceback (most recent call last):
  File "/home/acossairt/miniconda3/envs/ML_env/lib/python3.7/site-packages/deephyper/search/util.py", line 163, in generic_loader
    attr = load_attr_from(target)
  File "/home/acossairt/miniconda3/envs/ML_env/lib/python3.7/site-packages/deephyper/search/util.py", line 124, in load_attr_from
    module = importlib.import_module(str_module)
  File "/home/acossairt/miniconda3/envs/ML_env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hps_phoz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acossairt/miniconda3/envs/ML_env/bin/deephyper", line 8, in <module>
    sys.exit(main())
  File "/home/acossairt/miniconda3/envs/ML_env/lib/python3.7/site-packages/deephyper/core/cli/cli.py", line 51, in main
    func(**kwargs)
  File "/home/acossairt/miniconda3/envs/ML_env/lib/python3.7/site-packages/deephyper/core/cli/hps.py", line 36, in main
    search_obj = search_cls(**kwargs)
  File "/home/acossairt/miniconda3/envs/ML_env/lib/python3.7/site-packages/deephyper/search/hps/ambs.py", line 65, in __init__
    super().__init__(problem, run, evaluator, **kwargs)
  File "/home/acossairt/miniconda3/envs/ML_env/lib/python3.7/site-packages/deephyper/search/search.py", line 56, in __init__
    self.problem = util.generic_loader(problem, "Problem")
  File "/home/acossairt/miniconda3/envs/ML_env/lib/python3.7/site-packages/deephyper/search/util.py", line 167, in generic_loader
    raise GenericLoaderError(target, attribute, trace_source)
deephyper.core.exceptions.loading.GenericLoaderError: Traceback (most recent call last):
  File "/home/acossairt/miniconda3/envs/ML_env/lib/python3.7/site-packages/deephyper/search/util.py", line 163, in generic_loader
    attr = load_attr_from(target)
  File "/home/acossairt/miniconda3/envs/ML_env/lib/python3.7/site-packages/deephyper/search/util.py", line 124, in load_attr_from
    module = importlib.import_module(str_module)
  File "/home/acossairt/miniconda3/envs/ML_env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hps_phoz'

The attribute 'Problem' cannot be importe from 'hps_phoz.polynome2.pho_z_problem.Problem'.
